#pragma once

#include <algorithm>
#include <array>
#include <cstdint>

// Base forms from the official masters that the object sync includes although their type
// alone would exclude them. Runtime form ids; the official masters always load in the same order.
// Generated by Tools/activator_blocklist/generate_synced.py.
namespace SyncedWorldForms
{
// Lever and pull-chain furniture (TrapLever scripts): relayed like activators.
inline constexpr std::array<uint32_t, 8> kLeverFurniture{
    0x0003913A, // LeverPushAnimatingMetalNoPlayer
    0x00073128, // LeverPushAnimating
    0x00074A4E, // LeverPushAnimatingMetal
    0x000AA8C9, // LeverPushAnimatingPillarPuzzle
    0x000B7DB4, // LeverPushAnimatingNoPlayer
    0x00106513, // NorPullChainAnim01NoPlayer
    0x00109A7D, // GenPullChainAnim01NoPlayer
    0x02011ED4, // dlc1LeverPushAnimatingNoPlayeR
};

// Trees that yield an ingredient (lavender, mountain flowers, cabbages): harvested like flora.
inline constexpr std::array<uint32_t, 77> kHarvestableTrees{
    0x0001BB3D, // TreeFloraLavender01
    0x0008B5C4, // TestTreeFloraMountainFlower01Blue
    0x000B91F0, // TreeFloraThistle01
    0x000B91F8, // TreeFloraMountainFlower02Purple
    0x000BB947, // TreeFloraTundraCotton01
    0x000BB948, // TreeFloraJuniper01
    0x000BB949, // TreeFloraJazBay01
    0x000BB94A, // TreeFloraCanisRoot01
    0x000BB94B, // TreeFloraDeathBell01
    0x000BB94C, // TreeFloraDeathBell02
    0x000BB94D, // TreeFloraDragonsTongue01
    0x000BB94E, // TreeFloraDragonsTongue02
    0x000BB94F, // TreeFloraHangingMoss01
    0x000BB950, // TreeFloraHangingMoss02
    0x000BB951, // TreeFloraHangingMoss03
    0x000BB952, // TreeFloraLeek01
    0x000BB953, // TreeFloraWheat01
    0x000BCF33, // TreeFloraSnowberry01
    0x000BCF34, // TreeFloraSnowberry01Snow
    0x000BCF3A, // TreeFloraMountainFlower01Purple
    0x000BCF3C, // TreeFloraMountainFlower01Red
    0x000BCF3D, // TreeFloraMountainFlower01Blue
    0x000BCF3E, // TreeFloraMountainFlower02Red
    0x000BCF3F, // TreeFloraMountainFlower02Blue
    0x000BCF47, // TreeFloraPotatoPlant01
    0x000BCF48, // TreeFloraCabbage01
    0x000BE3E0, // TreeFloraSpikyGrass01
    0x000BE3E1, // TreeFloraSpikyGrass02
    0x000BE3E6, // TreeGourdCluster01
    0x000C43B0, // TreeFloraNightshade01
    0x000C43B6, // TreeFloraNightshade02
    0x000DF015, // TreeFloraSnowberry02
    0x02002A76, // DLC1TreeFloraMountainFlower01Yellow
    0x02002A77, // DLC1TreeFloraMountainFlower02Yellow
    0x0200A24D, // DLC01Gleamblossom01old
    0x0200B4EC, // DLC01AncestorsGladeTree
    0x0301045E, // BYOHHouseFloraCabbage01
    0x0301045F, // BYOHHouseFloraGourd01
    0x03010460, // BYOHHouseFloraLeek01
    0x03010461, // BYOHHouseIngrdCanisRoot01
    0x03010462, // BYOHHouseIngrdDeathbell01
    0x03010463, // BYOHHouseIngrdDragonTongue01
    0x03010464, // BYOHHouseIngrdGiantLichen01
    0x03010465, // BYOHHouseIngrdGlowMushrm01
    0x03010466, // BYOHHouseIngrdJazbay01
    0x03010467, // BYOHHouseIngrdJuniper01
    0x03010468, // BYOHHouseIngrdLavender01
    0x03010469, // BYOHHouseIngrdNightshade01
    0x030110B9, // BYOHHouseFloraCarrots01
    0x030110BA, // BYOHHouseFloraPotato01
    0x030110BB, // BYOHHouseIngrdCotton01
    0x030110BC, // BYOHHouseIngrdCreepCluster01
    0x030110BD, // BYOHHouseIngrdFungalPod01
    0x030110BE, // BYOHHouseIngrdMoraTap01
    0x030110BF, // BYOHHouseIngrdMtFlBlue01
    0x030110C0, // BYOHHouseIngrdMtFlPurple01
    0x030110C1, // BYOHHouseIngrdMtFlRed01
    0x030110C2, // BYOHHouseIngrdMushroom01
    0x030110C3, // BYOHHouseIngrdMushroom02
    0x030110C4, // BYOHHouseIngrdMushroom03
    0x030110C5, // BYOHHouseIngrdMushroom04
    0x030110C6, // BYOHHouseIngrdMushroom05
    0x030110C7, // BYOHHouseIngrdMushroom06
    0x030110C8, // BYOHHouseIngrdNirnroot01
    0x030110C9, // BYOHHouseIngrdScalyPBits01
    0x030110CA, // BYOHHouseIngrdSnowberry01
    0x030110CB, // BYOHHouseIngrdSpikyGrass01
    0x030110CC, // BYOHHouseIngrdThistle01
    0x030110CD, // BYOHHouseIngrdWheat01
    0x04016E24, // DLC2TreeFloraSpikyGrassAsh01
    0x04016E25, // DLC2TreeFloraSpikyGrassAsh02
    0x04017E93, // DLC2TreeFloraScathecraw01
    0x04017E94, // DLC2TreeFloraScathecraw02
    0x0401FF64, // DLC2TreeFloraHangingMoss01
    0x0401FF65, // DLC2TreeFloraHangingMoss02
    0x0401FF66, // DLC2TreeFloraHangingMoss03
    0x040206E8, // DLC2TreeFloraAshYam01
};

[[nodiscard]] inline bool IsLeverFurniture(const uint32_t aBaseFormId) noexcept
{
    return std::binary_search(kLeverFurniture.begin(), kLeverFurniture.end(), aBaseFormId);
}

[[nodiscard]] inline bool IsHarvestableTree(const uint32_t aBaseFormId) noexcept
{
    return std::binary_search(kHarvestableTrees.begin(), kHarvestableTrees.end(), aBaseFormId);
}
} // namespace SyncedWorldForms
